src/Entity/Contact.php
<?php

namespace App\Entity;

class Contact
{
    private $Nom;

    private $Email;

    private $Sujet; 

    private $Message;

    public function getNom()
    {
        return $this->Nom;
    }

    public function setNom(string $Nom)
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getEmail()
    {
        return $this->Email;
    }

    public function setEmail(string $Email)
    {
        $this->Email = $Email;

        return $this;
    }

    public function getSujet()
    {
        return $this->Sujet;
    }

    public function setSujet(string $Sujet)
    {
        $this->Sujet = $Sujet;

        return $this;
    }

    public function getMessage()
    {
        return $this->Message;
    }

    public function setMessage(string $Message)
    {
        $this->Message = $Message;

        return $this;
    }
}

src/Form/ConsultationEmailType.php
<?php

namespace App\Form;

use App\Entity\ConsultationEmail;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConsultationEmailType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Message', CKEditorType::class, [
                'attr' => [
                    'placeholder' => 'Votre message',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ConsultationEmail::class,
        ]); 
    }
}

src/Controller/Admin/ConsultationEmailController.php
<?php

namespace App\Controller\Admin;

use App\Entity\ConsultationEmail;
use App\Form\ConsultationEmailType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\ConsultationEmailRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/consultation/email')]
#[IsGranted('ROLE_ADMIN', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
class ConsultationEmailController extends AbstractController
{
    #[Route('/', name: 'app_admin_consultation_email_index', methods: ['GET'])]
    public function index(ConsultationEmailRepository $consultationEmailRepository): Response
    {
        return $this->render('admin/consultation_email/index.html.twig', [
            'consultation_emails' => $consultationEmailRepository->findBy(['Reponse' => null]),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_consultation_email_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ConsultationEmailRepository $consultationEmailRepository, $id): Response
    {
        $consultationEmail = new ConsultationEmail();
        $form = $this->createForm(ConsultationEmailType::class, $consultationEmail);
        $form->handleRequest($request);

        $consultation = $consultationEmailRepository->find($id);

        if ($form->isSubmitted() && $form->isValid()) {

            $consultationEmail->setMessage($form->get('Message')->getData());
            $consultationEmail->setUser($this->getUser()->getProfile());
            $consultationEmail->setReponse($consultation);
            $consultationEmailRepository->save($consultationEmail, true);

            return $this->redirectToRoute('app_admin_consultation_email_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/consultation_email/edit.html.twig', [
            'consultationemail' => $consultation,
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/user')]
#[IsGranted('ROLE_ADMIN', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_admin_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('admin/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/User/CartController.php
<?php

namespace App\Controller\User;

use Stripe\Stripe;
use App\Entity\TicketPaiement;
use App\Services\CartServices;
use App\Entity\SoldeCompteClient;
use App\Repository\TicketPaiementRepository;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\SoldeCompteClientRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CartController extends AbstractController
{
    public function __construct(
        private CartServices $cartServices,
        private MailerInterface $mailer
    ){}

    #[Route('/user/panier/{id}', name: 'user_panier')]
    #[IsGranted('ROLE_USER', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
    public function index(int $id)
    {
        $this->cartServices->add($id);

        return $this->redirectToRoute('user_panier_show');
    }

 
    #[Route('/user/panier', name: 'user_panier_show')]
    #[IsGranted('ROLE_USER', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
    public function show(): Response
    {
        $cardSData = $this->cartServices->getFullCart();
        $total = $this->cartServices->getTotal();

        return $this->render('user/forfait/cart.html.twig', [
            'products' => $cardSData,
            'total' => $total
        ]);
    }

    #[Route('/user/chekout', name: 'user_chekout')]
    #[IsGranted('ROLE_USER', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
    public function chekout()
    {
        $total = $this->cartServices->getTotal();

        $sripeSK = $_ENV['STRIPE_SK'];
        Stripe::setApiKey($sripeSK);

        $lineItems = [];
        foreach($this->cartServices->getFullCart() as $product) {
            $lineItems[] = [
                'price_data' => [
                    'currency' => 'eur',
                    'unit_amount' => $product['product']->getPriceTTC() * 100,
                    'product_data' => [
                        'name' => $product['product']->getName(),
                        'description' => $product['product']->getBonusProduct()->getName() . ' ' . $product['product']->getBonusProduct()->getPrice(),
                        ],
                        
                    ],
                'quantity' => $product['quantity'],
            ];
        }

        $session = \Stripe\Checkout\Session::create([
            'payment_method_types' => ['card'],
            'line_items' => $lineItems,
            'mode' => 'payment',
            'success_url' => "https://ursuliah.com/user/success?session_id={CHECKOUT_SESSION_ID}",
            'cancel_url' => $this->generateUrl('user_panier_show', [], UrlGeneratorInterface::ABSOLUTE_URL),
        ]);

        return $this->redirect($session->url, 303);
    }

    #[Route('/user/success', name: 'user_success')]
    #[IsGranted('ROLE_USER', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
    public function success(Request $request, TicketPaiementRepository $ticketPaiementRepository, SoldeCompteClientRepository $SoldeCompteClientRepository): Response
    {
        $cart = $this->cartServices->getFullCart();
        $name = array_column($cart, 'product');

        $sessionsID = $request->query->get('session_id');
        $stripe      = new \Stripe\StripeClient($_ENV['STRIPE_SK']);
        $session     = $stripe->checkout->sessions->retrieve($sessionsID);
        $paymentIntent = $stripe->paymentIntents->retrieve($session->payment_intent);
        $customer = $stripe->customers->retrieve($paymentIntent->customer);

        $TicketPaiement = new TicketPaiement();
        $TicketPaiement->setSecureKey($customer->id);
        $TicketPaiement->setTotalPaidTTC($paymentIntent->amount_received / 100);
        $TicketPaiement->setInvoiceNumber($customer->invoice_prefix);
        $TicketPaiement->setDiscount('0.00');
        $TicketPaiement->setNameProduct($name[0]->getName());
        $TicketPaiement->setCustomer($this->getUser()->getProfile()); // $this->getUser() is the current user
        $TicketPaiement->setCreatedAt(new \DateTimeImmutable());
        $ticketPaiementRepository->save($TicketPaiement, true);

        // prevoir un system de calcul sur le prix restant

        // pour le solde du compte client, je vais faire paiement + bonus
        $SoldeAvecBonus = $paymentIntent->amount_received / 100 + $name[0]->getBonusProduct()->getPrice();

        $soldeCompteClient = new SoldeCompteClient();
        $soldeCompteClient->setCustomer($this->getUser()->getProfile());
        $soldeCompteClient->setPrixRestant($SoldeAvecBonus);
        $SoldeCompteClientRepository->save($soldeCompteClient, true);

        $email = (new TemplatedEmail())
            ->from($_ENV['EMAIL_FROM'])
            ->to($this->getUser()->getEmail())
            ->subject('Votre paiement à été confirmé')
            ->htmlTemplate('email/email/confirmation_de_paiement.html.twig')
            ->context([
                'name' => $this->getUser()->getProfile()->getNom(),
                'address' => $this->getUser()->getProfile()->getAdresse(),
                'city' => $this->getUser()->getProfile()->getVille(),
                'postalCode' => $this->getUser()->getProfile()->getCodePostal(),
                'country' => $this->getUser()->getProfile()->getPays(),
                'invoiceNumber' => $customer->invoice_prefix,
                'forfait' => $name[0]->getName(),
                'total' => $paymentIntent->amount_received / 100,
                'discount' => '0.00',
            ]);
        $this->mailer->send($email);

        $this->cartServices->removeAll();

        return $this->render('user/forfait/success.html.twig', [
            'session' => $session,
            'paymentIntent' => $paymentIntent,
            'customer' => $customer,
        ]);


    }
}

src/Controller/User/Consultation/Tchat/TchatController.php
<?php

namespace App\Controller\User\Consultation\Tchat;



use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use DateTimeImmutable; 
use Lcobucci\JWT\Configuration;
use Lcobucci\JWT\Signer\Key\InMemory;
use Lcobucci\JWT\Signer\Hmac\Sha256;


class TchatController extends AbstractController
{
    #[Route('/user/tchat', name: 'tchat')]
    public function index(): Response
    {
        $username = $this->getUser()->getProfile()->getPseudo();

        $config = Configuration::forSymmetricSigner(new Sha256(), InMemory::plainText($this->getParameter('mercure_secret_key')));
        $token = $config->builder()
            ->withClaim('mercure', ['subscribe' => [sprintf("/%s", $username)]])
            ->getToken($config->signer(), $config->signingKey())
        ;

        $response =  $this->render('user/consultation_tchat/index.html.twig');

        $response->headers->setCookie(
            new Cookie(
                'mercureAuthorization',
                $token->toString(),
                (new \DateTime())
                    ->add(new \DateInterval('PT2H')),
                '/.well-known/mercure',
                null,
                false,
                true,
                false,
                'strict',

            )
        );

        return $response;
    }
}

src/Controller/User/DashboardController.php
<?php

namespace App\Controller\User;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DashboardController extends AbstractController
{
    #[Route('/user/dashboard', name: 'user_dashboard')]
    #[IsGranted('ROLE_USER', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
    public function index(): Response
    {
        return $this->render('user/dashboard/index.html.twig', [
            'controller_name' => 'DashboardController',
        ]);
    }
}

src/Controller/User/MesPaiementsController.php
<?php

namespace App\Controller\User;

use App\Services\PdfServices;
use App\Repository\TicketPaiementRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MesPaiementsController extends AbstractController
{
    #[Route('/user/paiements', name: 'app_mes_paiements')]
    #[IsGranted('ROLE_USER', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
    public function index(TicketPaiementRepository $ticket): Response
    {

        return $this->render('user/mes_paiements/index.html.twig', [
            'tickets' => $ticket->findBy(['Customer' => $this->getUser()->getProfile()]),
        ]);
    }

    #[Route('/user/paiements/pdf{id}', name: 'pdf_paiement')]
    #[IsGranted('ROLE_USER', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
    public function pdf(PdfServices $PdfServices, TicketPaiementRepository $ticket, $id)
    {
        $findPdf = $ticket->findOneBy(['id' => $id, 'Customer' => $this->getUser()->getProfile()]);
        $html = $this->render('user/mes_paiements/pdf.html.twig', ['facture' => $findPdf ]);
        $PdfServices->showPdfFile($html);

    }
}

src/Controller/User/ProductController.php
<?php

namespace App\Controller\User;

use App\Repository\ProductRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
    #[Route('/user/forfait', name: 'user_forfait')]
    #[IsGranted('ROLE_USER', message: 'Vous devez vous connecter pour accéder à cette page', statusCode: 404, exceptionCode: '404')]
    public function index(ProductRepository $product): Response
    {
        return $this->render('user/forfait/index.html.twig', [
            'products' => $product->findBy(['IsActive' => true])
        ]);
    }
} 

templates/user/consultation_email/PrixConsultationParEmail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="breadcumb-wrapper " data-bg-src="assets/img/bg/breadcumb-bg.jpg" data-overlay="black" data-opacity="7">
        <div class="container">
            <div class="breadcumb-content text-center">
                <h1 class="breadcumb-title">Blog Details</h1>
                <ul class="breadcumb-menu">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>Blog Details</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="th-checkout-wrapper space-top space-extra-bottom">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="container">
                        <div class="woocommerce-notices-wrapper">
                            <div class="woocommerce-message">Shipping costs updated.</div>
                        </div>
                        <section class="space pt-0" id="service-sec">
                            <div class="container">
                                <div class="row gy-30">
                                    {% for tarifConsultation in tarifConsultations %}
                                    <div class="col-md-6 col-lg-4">
                                        <div class="service-featured">
                                            <div class="service-featured_img">
                                                <img src="{{ asset('assets/img/service/service_box_1-1.jpg') }}" alt="service">
                                            </div>
                                            <div class="service-featured_content">
                                                <div class="service-bg-shape">
                                                    <img src="{{ asset('assets/img/service/service_box_shape1.jpg') }}" alt="img">
                                                </div>
                                                <div class="service-default-icon">
                                                    <img src="{{ asset('assets/img/icon/service-icon-1-1.svg') }}" alt="Icon">
                                                </div>
                                                <h3 class="box-title">
                                                    <a href="{{ path('user_consultation_email', {'Slug': tarifConsultation.Slug }) }}">
                                                        {{ tarifConsultation.Price |format_currency('EUR', {rounding_mode: 'floor'}) }}
                                                    </a>
                                                </h3>
                                                <p class="service-featured_text">{{ tarifConsultation.Description }}</p>
                                                <a href="{{ path('user_consultation_email', {'Slug': tarifConsultation.Slug }) }}" class="link-btn">
                                                    {{ tarifConsultation.Name }}<i class="fa-solid fa-arrow-up-right ms-2"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/consultation_email/consultation_e_mail.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="breadcumb-wrapper " data-bg-src="assets/img/bg/breadcumb-bg.jpg" data-overlay="black" data-opacity="7">
        <div class="container">
            <div class="breadcumb-content text-center">
                <h1 class="breadcumb-title">Blog Details</h1>
                <ul class="breadcumb-menu">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>Blog Details</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="th-checkout-wrapper space-top space-extra-bottom">
        <div class="container">
            <div class="row">
                {% include 'user/_partials/_navigation.html.twig' %}
                <div class="col-9">
                    <div class="container">
                        <div class="woocommerce-notices-wrapper">
                            <div class="woocommerce-message">Shipping costs updated.</div>
                        </div>
                        {{ form_start(form) }}
                        <div class="woocommerce-cart-form">
                            <table class="cart_table">
                                <tbody>

                                        <tr class="cart_item">
                                            <td data-title="Name">
                                                {{ form_widget(form.Message) }}
                                            </td>
                                        </tr>

                                </tbody>
                            </table>
                            <div class="th-cart-coupon">
                                <button type="submit" class="th-btn">Apply Coupon</button>
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/consultation_email/list.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="breadcumb-wrapper " data-bg-src="assets/img/bg/breadcumb-bg.jpg" data-overlay="black" data-opacity="7">
        <div class="container">
            <div class="breadcumb-content text-center">
                <h1 class="breadcumb-title">Blog Details</h1>
                <ul class="breadcumb-menu">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>Blog Details</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="th-checkout-wrapper space-top space-extra-bottom">
        <div class="container">
            <div class="row">
                {% include 'user/_partials/_navigation.html.twig' %}
                <div class="col-9">
                    <div class="container">
                        <div class="woocommerce-notices-wrapper">
                            <div class="woocommerce-message">Shipping costs updated.</div>
                        </div>
                        <table class="tinvwl-table-manage-list">
                            <thead>
                            <tr>
                                <th class="product-price">Expéditeur </th>
                                <th class="product-date">Destinataire</th>
                                <th class="product-stock">Message</th>
                                <th class="product-action">Date</th>
                                <th class="product-action"></th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for consultation in consultation_emails %}
                                <tr class="wishlist_item">
                                    <td class="product-price">
                                       Votre Voyant
                                    </td>
                                    <td class="product-date">
                                      {{ app.user.profile.nom }}
                                    </td>
                                    <td class="product-stock">
                                     {{ consultation.Message | u.truncate(10, '...') }}
                                    </td>
                                    <td class="product-action">
                                        {{ consultation.createdAt | date('d m Y') }}
                                    </td>
                                    <td class="product-action">
                                        <a href="{{ path('user_consultation_email_show', {'id': consultation.Id} ) }}" class="button">Voir la réponse</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/consultation_email/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="breadcumb-wrapper " data-bg-src="assets/img/bg/breadcumb-bg.jpg" data-overlay="black" data-opacity="7">
        <div class="container">
            <div class="breadcumb-content text-center">
                <h1 class="breadcumb-title">Blog Details</h1>
                <ul class="breadcumb-menu">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>Blog Details</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="th-checkout-wrapper space-top space-extra-bottom">
        <div class="container">
            <div class="row">
                {% include 'user/_partials/_navigation.html.twig' %}
                <div class="col-9">
                    <div class="container">
                        <div class="woocommerce-notices-wrapper">
                            <div class="woocommerce-message">Shipping costs updated.</div>
                        </div>
                        <div class="woocommerce-cart-form">
                            <table class="cart_table">
                                <tbody>
                                    <tr class="cart_item">
                                        <td data-title="Name">
                                            <p>La réponse de votre voyant</p>
                                            <p>{{ consultation.Message }}</p>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="woocommerce-cart-form">
                            <table class="cart_table">
                                <tbody>

                                <tr class="cart_item">
                                    <td data-title="Name">
                                        <p>Votre question</p>
                                        <p>{{ consultation.Reponse.Message }}</p>

                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 {% endblock %}