src/Entity/ArticleBlog.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\CreatedAtTrait;
use App\Entity\Traits\UpdatedAtTrait;
use App\Repository\ArticleBlogRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ArticleBlogRepository::class)]
#[Vich\Uploadable]
class ArticleBlog
{
    use CreatedAtTrait;
    use UpdatedAtTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Article = null;

    #[ORM\Column(length: 255)]
    private ?string $Slug = null;

    #[ORM\ManyToOne(inversedBy: 'articleBlogs')]
    private ?CategoryBlog $Categorie = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column]
    private ?bool $IsActive = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $LongDescription = null;

    #[Vich\UploadableField(mapping: 'article', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;
    
    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    public function __construct()
    {
        $this->CreatedAt = new DateTimeImmutable();
        $this->UpdatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticle(): ?string 
    {
        return $this->Article;
    }

    public function setArticle(string $Article): static
    {
        $this->Article = $Article;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): static
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getCategorie(): ?CategoryBlog
    {
        return $this->Categorie;
    }

    public function setCategorie(?CategoryBlog $Categorie): static
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->IsActive;
    }

    public function setIsActive(bool $IsActive): static
    {
        $this->IsActive = $IsActive;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->LongDescription;
    }

    public function setLongDescription(string $LongDescription): static
    {
        $this->LongDescription = $LongDescription;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->UpdatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }
}

src/Controller/VoyanceImmediateController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ModeDeConsultationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class VoyanceImmediateController extends AbstractController
{
    public function __construct(
        private ModeDeConsultationRepository $modeDeConsultationRepository
    ){}

    #[Route('/voyance-immediate/{Slug}', name: 'app_voyance_immediate')]
    public function index($Slug): Response
    {
        return $this->render('voyance_immediate/index.html.twig', [
            'modeDeConsultation' => $this->modeDeConsultationRepository->findOneBy(['Slug' => $Slug])
        ]);
    }
}

templates/voyance_immediate/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
 <div class="breadcumb-wrapper " data-bg-src="{{ asset('assets/img/breadcrum/' ~ modeDeConsultation.Slug ~ '.png') }}" data-overlay="black" data-opacity="7">
        <div class="container">
            <div class="breadcumb-content text-center">
                <h1 class="breadcumb-title">{{ modeDeConsultation.titre }}</h1>
                <ul class="breadcumb-menu">
                    <li><a href="{{ path('app_main') }}">Accueil</a></li>
                    <li>{{ modeDeConsultation.titre }}<</li>
                </ul>
            </div>
        </div>
    </div>

    <section class="space-top space-extra2-bottom">
        <div class="container">
            <div class="row">
                <div class="col-xxl-8 col-lg-8">
                    <div class="page-single">
                        <div class="page-img mb-30">
                            <img src="{{ vich_uploader_asset(modeDeConsultation, 'imageFile') }}" alt="Service Image">
                        </div>
                        <div class="page-content">
                            {{ modeDeConsultation.GrandeDescription | raw }}
                        </div>
                    </div>
                </div>
                <div class="col-xxl-4 col-lg-4">
                    <aside class="sidebar-area">
                        <div class="widget widget_categories  ">
                            <h3 class="widget_title">Voyance en ligne</h3>
                            <ul>
                                <li><a href="{{ path('app_voyance_immediate', {'Slug': 'voyance-par-tchat'}) }}">Voyance Tchat</a></li>
                                <li><a href="{{ path('app_voyance_immediate', {'Slug': 'voyance-par-email'}) }}">Voyance par Email</a> </li>
                                <li><a href="{{ path('app_voyance_immediate', {'Slug': 'voyance-par-telephone'}) }}">Voyance par téléphone</a></li>
                            </ul>
                        </div>
                        
                        <div id="btn-home" class="btn-group" style="gap: 1px; text-align:center"></div>

                    </aside>
                    
                </div>
            </div>
        </div>
    </section>

    <section class="cta-area-3 bg-theme" data-bg-src="assets/img/bg/newsletter-bg.png">
        <div class="cta-thumb3 shape-mockup d-lg-block d-none" data-top="0" data-left="0"><img src="assets/img/bg/cta-bg3.png" alt="img"></div>
        <div class="container">
            <div class="row justify-content-end align-items-center">
                <div class="col-lg-6 col-md-7">
                    <div class="title-area mb-0 me-xl-5 text-md-start text-center">
                        <h2 class="sec-title h3 text-white">Inscrivez-vous gratuitement</h2>
                    </div>
                </div>
                <div class="col-lg-3 col-md-5 mt-40 mt-md-0 text-md-end text-center">
                    <a href="{{ path('app_register') }}" class="th-btn style2">Inscrivez-vous<i class="fa-regular fa-arrow-right ms-2"></i></a>
                </div>
            </div>
        </div>
    </section>

{% endblock %}